Repository UMC-UPSTYLE/upstyle-android, pull requests merged in 2025-02, with the labels that each got.

#39 Feature: 계정, 내 프로필 화면, 일부 기능 구현
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/com/umc/upstyle/AccountFragment.kt
  app/src/main/java/com/umc/upstyle/MyProfileFragment.kt
  app/src/main/java/com/umc/upstyle/Outer1Activity.kt
  app/src/main/res/drawable/myprofilebtn.xml
  app/src/main/res/layout/activity_outer_1.xml
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/layout/fragment_my_profile.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
Labels: feat

#43 Feature: 계정 화면, 기능 구현 완료
  app/src/main/java/com/umc/upstyle/AccountFragment.kt
  app/src/main/java/com/umc/upstyle/CategoryFragment.kt
  app/src/main/java/com/umc/upstyle/LogoutPopupDialog.kt
  app/src/main/java/com/umc/upstyle/MyProfileFragment.kt
  app/src/main/java/com/umc/upstyle/TodayOotdFragment.kt
  app/src/main/java/com/umc/upstyle/WebViewFragment.kt
  app/src/main/res/drawable/ic_namechk_gray.xml
  app/src/main/res/drawable/ic_namechk_red.xml
  app/src/main/res/drawable/ic_namechk_white.xml
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/layout/fragment_my_profile.xml
  app/src/main/res/layout/fragment_web_view.xml
  app/src/main/res/layout/logout_popup.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feat

#47 Feat: 글쓰기 화면 기능 추가
  app/src/main/java/com/umc/upstyle/ChatFragment.kt
  app/src/main/java/com/umc/upstyle/CreateRequestFragment.kt
  app/src/main/java/com/umc/upstyle/CreateVoteFragment.kt
  app/src/main/java/com/umc/upstyle/LoadCategoryFragment.kt
  app/src/main/java/com/umc/upstyle/LoadItemFragment.kt
  app/src/main/java/com/umc/upstyle/VotePopupDialog.kt
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/layout/fragment_create_request.xml
  app/src/main/res/layout/fragment_create_vote.xml
  app/src/main/res/layout/fragment_load_category.xml
  app/src/main/res/layout/photo_popup.xml
  app/src/main/res/layout/vote_popup.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/styles_login.xml
Labels: feat

#48 Fix: 프래그먼트 이동해도 텍스트 유실되지 않게 수정
  app/src/main/java/com/umc/upstyle/CreateRequestFragment.kt
  app/src/main/java/com/umc/upstyle/CreateVoteFragment.kt
  app/src/main/java/com/umc/upstyle/data/viewmodel/PostViewModel.kt
  app/src/main/java/com/umc/upstyle/data/viewmodel/RequestViewModel.kt
  app/src/main/res/layout/fragment_create_request.xml
  app/src/main/res/layout/fragment_create_vote.xml
Labels: fix

#50 Feat+Fix: TodayOotdFragment API 연결&ViewModel로 변경&사진 촬영 오류 해결
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/upstyle/CategoryFragment.kt
  app/src/main/java/com/umc/upstyle/ColorFragment.kt
  app/src/main/java/com/umc/upstyle/EtcFragment.kt
  app/src/main/java/com/umc/upstyle/FitFragment.kt
  app/src/main/java/com/umc/upstyle/NetworkModule.kt
  app/src/main/java/com/umc/upstyle/SizeFragment.kt
  app/src/main/java/com/umc/upstyle/TodayOotdFragment.kt
  app/src/main/java/com/umc/upstyle/data/model/ClothRequestDTO.kt
  app/src/main/java/com/umc/upstyle/data/model/OOTDRequest.kt
  app/src/main/java/com/umc/upstyle/data/network/OOTDService.kt
  app/src/main/java/com/umc/upstyle/data/network/RetrofitClient.kt
  app/src/main/java/com/umc/upstyle/data/viewmodel/ClothViewModel.kt
  app/src/main/java/com/umc/upstyle/utils/CategoryUtil.kt
  app/src/main/java/com/umc/upstyle/utils/ColorUtil.kt
  app/src/main/java/com/umc/upstyle/utils/FitUtil.kt
  app/src/main/java/com/umc/upstyle/utils/SizeUtil.kt
  app/src/main/res/xml/file_path.xml
  build.gradle.kts
Labels: feat, fix

#54 Feat: Post Detail Fragment
  app/src/main/java/com/umc/upstyle/AdapterDay.kt
  app/src/main/java/com/umc/upstyle/ClosetFragment.kt
  app/src/main/java/com/umc/upstyle/ClosetItemFragment.kt
  app/src/main/java/com/umc/upstyle/MyHomeFragment.kt
  app/src/main/java/com/umc/upstyle/OotdDetailFragment.kt
  app/src/main/java/com/umc/upstyle/PostDetailFragment.kt
  app/src/main/java/com/umc/upstyle/TodayOotdFragment.kt
  app/src/main/java/com/umc/upstyle/ViewVoteFragment.kt
  app/src/main/java/com/umc/upstyle/data/model/VoteDetailResponse.kt
  app/src/main/java/com/umc/upstyle/data/network/RetrofitClient.kt
  app/src/main/java/com/umc/upstyle/data/network/VoteService.kt
  app/src/main/res/layout/fragment_post_detail.xml
  app/src/main/res/layout/fragment_view_vote.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feat

#59 Api4 yh
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/upstyle/BottomSheetViewFragment.kt
  app/src/main/java/com/umc/upstyle/CodiBottomSheetDialogFragment.kt
  app/src/main/java/com/umc/upstyle/CreateRequestFragment.kt
  app/src/main/java/com/umc/upstyle/CreateVoteFragment.kt
  app/src/main/java/com/umc/upstyle/MyApplication.kt
  app/src/main/java/com/umc/upstyle/PostDetailFragment.kt
  app/src/main/java/com/umc/upstyle/RequestDetailFragment.kt
  app/src/main/java/com/umc/upstyle/ResponseAdapter.kt
  app/src/main/java/com/umc/upstyle/TodayOotdFragment.kt
  app/src/main/java/com/umc/upstyle/VoteOptionAdapter.kt
  app/src/main/java/com/umc/upstyle/data/model/OOTDRequest.kt
  app/src/main/java/com/umc/upstyle/data/model/RequestResponse.kt
  app/src/main/java/com/umc/upstyle/data/model/VoteDetailResponse.kt
  app/src/main/java/com/umc/upstyle/data/network/OOTDService.kt
  app/src/main/java/com/umc/upstyle/data/network/RequestService.kt
  app/src/main/java/com/umc/upstyle/data/network/VoteService.kt
  app/src/main/java/com/umc/upstyle/data/viewmodel/ClothViewModel.kt
  app/src/main/res/drawable/bg_bottom_sheet_gray.xml
  app/src/main/res/drawable/bg_white_line_10.xml
  app/src/main/res/drawable/bg_white_line_999.xml
  app/src/main/res/drawable/bg_yellow_10.xml
  app/src/main/res/drawable/bg_yellow_30.xml
  app/src/main/res/drawable/line_bottom_sheet.xml
  app/src/main/res/layout/fragment_bottom_sheet_view.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_codi_bottom_sheet_dialog.xml
  app/src/main/res/layout/fragment_create_request.xml
  app/src/main/res/layout/fragment_create_vote.xml
  app/src/main/res/layout/fragment_post_detail.xml
  app/src/main/res/layout/fragment_request_detail.xml
  app/src/main/res/layout/fragment_vote.xml
  app/src/main/res/layout/item_response.xml
  app/src/main/res/layout/item_vote_option.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/file_path.xml
  gradle/libs.versions.toml
Labels: feat, fix

#63 코디 요청 응답 보기+댓글 등록 기능 구현+불필요한 코드 삭제
  .idea/gradle.xml
  app/build.gradle.kts
  app/src/main/java/com/umc/upstyle/BottomSheetViewFragment.kt
  app/src/main/java/com/umc/upstyle/CodiBottomSheetDialogFragment.kt
  app/src/main/java/com/umc/upstyle/CreateRequestFragment.kt
  app/src/main/java/com/umc/upstyle/CreateVoteFragment.kt
  app/src/main/java/com/umc/upstyle/LoadCategoryFragment.kt
  app/src/main/java/com/umc/upstyle/LoadItemFragment.kt
  app/src/main/java/com/umc/upstyle/MyHomeFragment.kt
  app/src/main/java/com/umc/upstyle/RequestDetailFragment.kt
  app/src/main/java/com/umc/upstyle/ResponseFragment.kt
  app/src/main/java/com/umc/upstyle/TodayOotdFragment.kt
  app/src/main/java/com/umc/upstyle/data/model/RequestResponse.kt
  app/src/main/java/com/umc/upstyle/data/network/RequestService.kt
  app/src/main/java/com/umc/upstyle/utils/CategoryUtil.kt
  app/src/main/res/layout/activity_myhome.xml
  app/src/main/res/layout/fragment_codi_bottom_sheet_dialog.xml
  app/src/main/res/layout/fragment_load_category.xml
  app/src/main/res/layout/fragment_request_detail.xml
  app/src/main/res/layout/list_item_day.xml
  gradle/libs.versions.toml
Labels: cleanup, feat, fix

#64 투표 글 작성 기능 구현 api 연결까지 완료🥹
  app/src/main/java/com/umc/upstyle/CreateVoteFragment.kt
  app/src/main/java/com/umc/upstyle/LoadCategoryFragment.kt
  app/src/main/java/com/umc/upstyle/PostAdapter.kt
  app/src/main/java/com/umc/upstyle/ResponseFragment.kt
  app/src/main/java/com/umc/upstyle/VoteFragment.kt
  app/src/main/java/com/umc/upstyle/VoteItemAdapter.kt
  app/src/main/java/com/umc/upstyle/data/model/Vote.kt
  app/src/main/java/com/umc/upstyle/data/model/VoteItem.kt
  app/src/main/java/com/umc/upstyle/data/network/VoteService.kt
  app/src/main/java/com/umc/upstyle/data/viewmodel/CategoryViewModel.kt
  app/src/main/java/com/umc/upstyle/data/viewmodel/PostViewModel.kt
  app/src/main/java/com/umc/upstyle/data/viewmodel/ResponseViewModel.kt
  app/src/main/res/layout/fragment_create_request.xml
  app/src/main/res/layout/fragment_create_vote.xml
  app/src/main/res/layout/fragment_post_detail.xml
  app/src/main/res/layout/item_post.xml
  app/src/main/res/layout/item_request.xml
  app/src/main/res/layout/item_vote.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feat

#65 Feat: OOTD 등록화면 로딩창 추가
  app/src/main/java/com/umc/upstyle/TodayOotdFragment.kt
  app/src/main/res/layout/activity_today_ootd.xml
Labels: feat

#68 Feat: SearchItem -> SearchResult -> BookmarkOotd 구현
  app/src/main/java/com/umc/upstyle/BookmarkOotdFragment.kt
  app/src/main/java/com/umc/upstyle/Item_result.kt
  app/src/main/java/com/umc/upstyle/Item_search.kt
  app/src/main/java/com/umc/upstyle/RecyclerAdapter_Result.kt
  app/src/main/java/com/umc/upstyle/RecyclerAdapter_Search.kt
  app/src/main/java/com/umc/upstyle/RequestDetailFragment.kt
  app/src/main/java/com/umc/upstyle/SearchResultFragment.kt
  app/src/main/java/com/umc/upstyle/data/model/Cloth.kt
  app/src/main/java/com/umc/upstyle/data/model/ClothPreview.kt
  app/src/main/java/com/umc/upstyle/data/model/ClothesCategoryResponse.kt
  app/src/main/java/com/umc/upstyle/data/model/Ootd.kt
  app/src/main/java/com/umc/upstyle/data/model/User.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_bookmark_ootd.xml
  app/src/main/res/layout/fragment_search_result.xml
Labels: feat

#72 Feat: 북마크 관련 api 연결 수정
  app/src/main/java/com/umc/upstyle/BookmarkFragment.kt
  app/src/main/java/com/umc/upstyle/BookmarkOotdFragment.kt
  app/src/main/java/com/umc/upstyle/data/model/BookmarkRequest.kt
  app/src/main/java/com/umc/upstyle/data/network/Apiservice.kt
  app/src/main/res/layout/fragment_bookmark_ootd.xml
  app/src/main/res/layout/recycler_item_bookmark.xml
Labels: feat
